"""initial migration

Revision ID: 1b33292593a9
Revises:
Create Date: 2025-03-03 15:48:05.489206

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1b33292593a9"
down_revision: Union[str, None] = None

branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False, autoincrement=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("price", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("brand", sa.String(length=64), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "specifications",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_id"), "products", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=255), nullable=True),
        sa.Column("gender", sa.String(length=64), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("hobbies", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("search_history", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "lifestyle_preferences",
            postgresql.ARRAY(sa.String()),
            nullable=True,
        ),
        sa.Column("location", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "product_images",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_image_id"), "product_images", ["id"], unique=False)

    op.create_table(
        "features",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("feature_name", sa.String(length=255), nullable=False, unique=True),
        sa.Column(
            "categories",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
    )
    
    op.create_table(
        "product_reviews",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("user_name", sa.String(length=255), nullable=True),
        sa.Column("review", sa.Text(), nullable=True),
        sa.Column("rating", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("feature_id", sa.Integer(), nullable=True),
        sa.Column("sentiment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["feature_id"], ["features.id"], ondelete="SET NULL", name="fk_review_feature"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_review_id"), "product_reviews", ["id"], unique=False)

    # Variants Table
    op.create_table(
        "variants",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("in_stock", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_variants_id", "variants", ["id"], unique=False)

    # Variant Attributes Table (Junction Table)
    op.create_table(
        "variant_attributes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.Integer(), nullable=False),
        sa.Column("attribute_name", sa.String(length=128), nullable=False),
        sa.Column("attribute_value", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["variant_id"], ["variants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_variant_attributes_id",
        "variant_attributes",
        ["id"],
        unique=False,
    )
    op.create_table(
        "personalized_product_sections",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "personalization",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "done",
                "failed",
                name="personalized_product_section_status",
            ),
            nullable=False,
        ),
        sa.Column("phoenix_trace_id", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("product_id", "user_id"),
    )

    op.create_table(
        "product_features",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("feature_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["feature_id"], ["features.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("product_id", "feature_id", name="uq_product_feature"),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    
    # Drop dependent tables first
    op.drop_index("ix_variant_attributes_id", table_name="variant_attributes")
    op.drop_table("variant_attributes")

    op.drop_index("ix_variants_id", table_name="variants")
    op.drop_table("variants")

    # Drop other tables
    op.drop_index(op.f("ix_review_id"), table_name="product_reviews")
    op.drop_table("product_reviews")

    op.drop_index(op.f("ix_product_image_id"), table_name="product_images")
    op.drop_table("product_images")

    op.drop_table("personalized_product_sections")

    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")

    op.drop_table("product_features")

    op.drop_table("features")

    # Finally, drop the product table
    op.drop_index(op.f("ix_product_id"), table_name="products")
    op.drop_table("products")

    # Drop the enum type
    op.execute("DROP TYPE personalized_product_section_status")
